//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeeform
    {
        public string Firstname { get; set; } 
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public byte[] ProfilePicture { get; set; }
        public string Position { get; set; }
        public int EmpId { get; set; }
    }
}
